### ISSUE TITLE
New Feature: Support syncing user-level settings

### ISSUE THREAD

**Issue by Spitfire1900** [dangmai/vscode-workspace-default-settings#314]
Support specifying a URL (e.g. Bitbucket/Github raw URL like https://github.com/myorg/vscode-settings/raw/main/settings.default.json) to sync user settings. Configuration for the extension itself would be very good to put in for example:

```jsonc
"files.associations": {
    "**/settings.default.json": "jsonc"
},
"json.schemas": [
    {
        "fileMatch": [
            "/.vscode/settings.default.json"
        ],
        "url": "vscode://schemas/settings/folder"
    }
],
"workspace-default-settings.jsonIndentation": 4,
"workspace-default-settings.runOnActivation": true,
 ```

**Comment by dangmai** [comment]
While I understand the convenience factor that the feature request can bring, I'm not planning on adding support for it. There are a few reasons for this:

- This extension really is meant to be a very simple layer of configuration to help enforcing team-wide settings, and I don't want to add complexities to it. This request, in particular, comes with reading a configuration file from an arbitrary URL, which increases the attack surface significantly.
- This behavior can be done by other extensions/tools. Since you specify that you'd want this to be user-level settings, you can use VSCode built-in settings sync or many other extensions to do it instead. I do this in my own set up to set up JSON schemas for tools that I regularly use.
