### ISSUE TITLE
I can't find any extension settings

### ISSUE THREAD

**Issue by oakmegaeddie** [dangmai/vscode-workspace-default-settings#327]
In README, it says this extension has following setting:

- workspace-default-settings.runOnActivation
- workspace-default-settings.jsonIndentation
- workspace-default-settings.defaultSettingsFileName

But I can't find any.

<img width="523" alt="截圖 2023-05-26 12 11 05" src="https://github.com/dangmai/vscode-workspace-default-settings/assets/82018290/46a4e291-9fc0-446b-ac93-1eba18e6dfcf">

**Comment by dangmai** [comment]
Hi, if you're using the GUI to change your settings, then you can just search by "Workspace Default Settings" and you'll see the settings supported by the extension. For example here's a screenshot in my VSCode:


<img width="1201" alt="Screenshot 2023-05-27 at 4 35 21 PM" src="https://github.com/dangmai/vscode-workspace-default-settings/assets/1305527/dbc7e7d4-c108-4284-a99c-8ea868f27260">

When I search by `@ext:dangmai.workspace-default-settings` I also find these settings, so I'm not really sure what's going on with your setup. Are you sure that the extension is enabled in your VSCode instance?

Closing this since it's a question instead of an issue, feel free to add more comments if it's still not working.
